### ISSUE TITLE
Template Inheritance

### ISSUE THREAD

**Issue by coursar** [Sokolovskaia/HW9_Tele2#8]
Мы пока это ещё не проходили, но вы уже можете внедрить: http://flask.pocoo.org/docs/1.0/patterns/templateinheritance/

Поскольку актуальные от архивных отличаются только заголовками, вы вывод таблички тарифов можете вынести в отдельный блок

**Comment by Sokolovskaia** [comment]
Когда применила наследование шаблнов, столкнулась с таким вопросом. Тело цикла for совпадает для actual и archive. Меняется только сам итерируемый словарь (actual или archive). Соответственно хотела оставить тело цикла в родительском шаблоне base.html.  А имя итерируемого объекта поместить в блок и записать в index.html и archive.html.  Но в таком случае при запуске выдается ошибка, что не находится item. Как решить эту проблему?

**Comment by coursar** [comment]
Ну вы бы залили пример-то ))

**Comment by coursar** [comment]
См. Pull Request
